"""empty message

Revision ID: 33d8ef6c265d
Revises: bc4dbd7e7eb6
Create Date: 2021-01-21 16:32:10.298286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33d8ef6c265d'
down_revision = 'bc4dbd7e7eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True, comment='标题'),
    sa.Column('summary', mysql.TEXT(), nullable=True, comment='摘要'),
    sa.Column('authors', mysql.VARCHAR(length=1000), nullable=True, comment='作者'),
    sa.Column('pmid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='PMID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
